name: "zborowa"
title: "zborowa"
description: "Personal blog to write about interesting findings and experiments."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
theme: jekyll-theme-minimal
